apiVersion: v1
kind: Service
metadata:
  name: vfda-be
  namespace: default
  labels:
    app: vfda-be
    service: vfda-be
    deploy_by: thai
spec:
  type: ClusterIP 
  ports:
    - name: http
      protocol: TCP
      port: 8005      
      targetPort: 8005
  selector:
    app: vfda-be
